### PR TITLE
fix update logic and allow any boss to be detected

### PR DESCRIPTION
**Pull request by Nelgamix**
Rewrite the logic for knowing when to increase the wave number.
I removed all the static variables for each boss, as we don't need to know which one spawned to be able to know when a wave starts.
The idea is to detect a change in the number of living bosses in the boss rush room :
* When we enter the room, no entity are inside, so wasHasStarted is false
* When the bosses spawn, we detect that they spawn, and set wasHasStarted to true and increase the wave number
* While the bosses are still alive, waveHasStarted will stay true, so we don't increase the wave number
* When the bosses are dead, we detect that no boss entity are still alive in the room and put waveHasStarted to false again
* Repeat 2+
I'm not 100 % sure it covers all combinations of bosses, but I tested it with "debug 10" multiple times, and one time normally, and it worked :)

### CODE REVIEW

**Comment by AaronCohen21** [comment]
Thanks for the PR, I'm quite busy at the moment so I don't know when I'll be able to test it to make sure it works before merging.

In the meantime, can you test the mod's functionality by going into boss rush and spawning larry jr and fistula at the same time?

If you don't start the boss rush sequence by taking an item and spawn the two bosses instead, it should simulate a wave being spawned. The reason I'm asking you to do this is because it is a common problem I ran into during original development, and a problem that other implementations of the algorithm have encountered. When you kill part of larry jr causing him to split into two, or kill fistula and cause it to split, there is a good chance that your logic may bug out and accidentally increment the counter. That is the reason why there are all of the static variables in the code to ensure that all bosses can only spawn once, and bosses "splitting" won't increment the counter.

An idea that I've had but haven't had the time to implement is removing the static variables and instead adding "seen" boss ID numbers into a dictionary and checking the dictionary each time a new boss spawns rather than the massive if/elseif block.

Regardless, please review #2 as it had the same issue I have mentioned. If your code still works after testing for the issue let me know, and I'll test the implementation once exams season is over.

**Comment by Nelgamix** [comment]
Thanks for the detailed answer.
I did test everything again, as I wasn't sure that I didn't break MCM because I didn't have it when I first tested.
I fixed the MCM part and cleaned a little bit, and I found some problems with some bosses (blastocyst for exemple, because if killed last, it will separate into two other mobs with a small delay so the wave was detected as finished even thought it was not the case), but it should be fixed now.
I will try the particular case you mentionned, and tell you if it works, but since I have encountered them in my many tests now, it should be good.
Also, if you have any comment on the code style itself, please let me know. I'm not really familiar with Lua, so I tried to clean a little bit to be able to understand better, but I might have done something not correctly.

**Comment by Nelgamix** [comment]
I did the test that you mentionned several times, and also the one with Blastocyst. It works as expected, only increasing the wave counter when initially spawned, and not when they split.

I also added some logs to see what was happening, here is an extract for Fistula and Larry jr (x5 because each spawn adds one body, and only one spawn does nothing since it immediately dies) :
```
[INFO] - Lua Debug: Number of alive bosses: 12
[INFO] - Lua Debug: Increase wave number
[INFO] - Lua Debug: Number of alive bosses: 6
[INFO] - TriggerBossDeath: 5 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 5
[INFO] - Lua Debug: Number of alive bosses: 9
[INFO] - TriggerBossDeath: 8 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 8
[INFO] - TriggerBossDeath: 7 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 7
[INFO] - TriggerBossDeath: 6 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 6
[INFO] - Lua Debug: Number of alive bosses: 8
[INFO] - TriggerBossDeath: 7 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 7
[INFO] - TriggerBossDeath: 6 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 6
[INFO] - TriggerBossDeath: 5 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 5
[INFO] - Action PillCard Triggered
[INFO] - TriggerBossDeath: 4 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 4
[INFO] - TriggerBossDeath: 3 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 3
[INFO] - Lua Debug: Number of alive bosses: 5
[INFO] - TriggerBossDeath: 4 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 4
[INFO] - TriggerBossDeath: 3 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 3
[INFO] - TriggerBossDeath: 2 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 2
[INFO] - Lua Debug: Number of alive bosses: 4
[INFO] - TriggerBossDeath: 3 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 3
[INFO] - Lua Debug: Number of alive bosses: 5
[INFO] - TriggerBossDeath: 4 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 4
[INFO] - TriggerBossDeath: 3 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 3
[INFO] - TriggerBossDeath: 2 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 2
[INFO] - TriggerBossDeath: 1 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 1
[INFO] - TriggerBossDeath: 0 bosses remaining.
[INFO] - deathspawn_boss, color idx -1
[INFO] - Lua Debug: Number of alive bosses: 0
[INFO] - Lua Debug: Wave has finished
```

I'm not sure why it starts at 12 while it should be 6, but it does not alter the behaviour of the code because we check for at least one boss, and after splitting, the number simply increase by one, so it should be good.

Test with Blastocyst :
```
[INFO] - Lua Debug: Number of alive bosses: 2
[INFO] - Lua Debug: Increase wave number
[INFO] - Lua Debug: Number of alive bosses: 1
[INFO] - Lua Debug: Number of alive bosses: 3
[INFO] - TriggerBossDeath: 2 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 2
[INFO] - Lua Debug: Number of alive bosses: 4
[INFO] - TriggerBossDeath: 3 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 3
[INFO] - Lua Debug: Number of alive bosses: 5
[INFO] - TriggerBossDeath: 4 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 4
[INFO] - TriggerBossDeath: 3 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 3
[INFO] - TriggerBossDeath: 2 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 2
[INFO] - Queued Path music/Afterbirth/Pulso Profundum (dank Depths ) Layer.ogg
[INFO] - Queued Path music/Afterbirth/Pulso Profundum (dank Depths ) Loop.ogg
[INFO] - TriggerBossDeath: 1 bosses remaining.
[INFO] - Lua Debug: Number of alive bosses: 1
[INFO] - TriggerBossDeath: 0 bosses remaining.
[INFO] - deathspawn_boss, color idx -1
[INFO] - Lua Debug: Number of alive bosses: 0
[INFO] - Lua Debug: Wave has finished
```
I could record some sequences with the tests I do if you don't have the time.

Finally, regarding the solution with the dictionary, that's what I first thought I would try. But if we can keep the solution in this PR, I think it should be better, because it's simpler and more performant.

**Comment by AaronCohen21** [comment]
Everything here looks really good. Regarding the code style don't even worry about it. This mod was literally the first time I ever used Lua so I'm just as new as you are.

One more test case I forgot about is using the Meat Cleaver active item during a wave. As your update logic checks to see if all bosses have been killed and new ones then spawn to start a new wave, this item could possibly interfere with the update logic (it happened early in development for me as well).

I also agree about the dictionary solution being a separate issue. It would require the entire algorithm to be scrapped and reworked from the ground up. We shouldn't need to worry about that right now as the current method works.

In about a week I'll have the time to do a full code review and test it myself before merging the PR. Things are just quite busy right now so I won't be able to look at it immediately.

**Comment by Nelgamix** [comment]
No problem, I'll let you check everything and make sure I didn't break anything.

Also, I've quickly tested yesterday with the Meat Cleaver item, and as I expected, it seems to works just fine.
Based on how its implemented, I'd say that the only type of thing that could break the counter is if somehow a boss is detected as dead (and also was the last one in the room) but is not really dead, and just "revives" into another form after a short delay or animation. In this case, the counter will be incremented as if it was a new wave while it's not. Things like Satan for exemple, when in the transition from P1 to P2. However, every example I have in mind is a special boss, and they will not spawn in the boss rush. If you have any idea, I'll test it.

I think using the function provided in `Room` (`getAliveBossesCount`) for this is a good solution, unless there is an edge case I missed due to the lack of documentation and/or knowledge of the game.
The first implementation I did was to check myself for each entity in the room and counting them, but it is not the same behaviour since it was not working properly with Blastocyst.
https://wofsauge.github.io/IsaacDocs/rep/Room.html#getalivebossescount

**Comment by AaronCohen21** [comment]
Hey!

I just had the time to test everything you've changed and it all looks good! I'm gonna merge the changes and update the workshop page with the new logic.

Thanks so much for contributing!

**Pull request merged**
